version: "3.9"
services:
  rstudio:
    image: "${IMAGE}" 
    ports:
      - "8787:8787"
    volumes:
      - type: "bind"
        source: "${WORKING_DIR}"
        target: "/home/rstudio"
      - type: "bind"
        source: "${RSTUDIO}"
        target: "/home/rstudio/.config/rstudio"