---
title: "Precios Argentina"
output:
  flexdashboard::flex_dashboard:
     theme : spacelab
     orientation : rows 
     self_contained : TRUE
     css: www/styles.css
     navbar:
       - { title: "Fuente: Indec", href: "https://www.indec.gob.ar/", align: right}
runtime: shiny
---



```{r setup, include=FALSE}

#https://fontawesome.com/icons/chart-simple?s=solid
#https://shiny.rstudio.com/tutorial/written-tutorial/lesson3/
#https://fontawesome.com/v4/cheatsheet/



library(flexdashboard)
library(tidyverse)
library(shiny)
library(readxl)
library(highcharter)
library(RColorBrewer)



indec = read_excel("indecnacional.xlsx")

indec$period_filter = substr(as.Date(indec$periodos), 1, 7)



interanual <- function(df, val){
    values = c()
    for (i in 0:11) {
        value_lag = lag((pull((df[,c(val)]) / 100) + 1), i)[nrow(df)]
        values[i + 1] <- value_lag}
    product = (prod(values) - 1) * 100
    return(round(product,1))
}

valuebox_mensual = function(data, inputy) {
  valueBox(
    value = tags$p(paste0(pull(data[,c(inputy)])[nrow(data)], ' %'),
                   style = "font-size: 100%; color: #ffffff"), 
    icon = "fa-diamond",
    caption = tags$p(paste0(substr(data$periodos[nrow(data)],1,7), ' ',inputy,' : Mensual'), 
                     style = "font-size: 100%; color: #ffffff"),
    color = '#237d75')
  
}



valuebox_interanual = function(data, inputy) {
  
  valueBox(value = tags$p(paste0(interanual(data, inputy), ' %'), 
                          style = "font-size: 100%; color: #ffffff"), 
           icon = "fa-line-chart",
           caption = tags$p(paste0(paste0('Desde: ',substr(data$periodos[nrow(data) - 12],1,7), ' Hasta ', substr(data$periodos[nrow(data)],1,7)), '. Interanual.'), style = "font-size: 100%; color: #ffffff"),
           color = '#525cd1')
  
}


valuebox_mayor = function(data) {
  
  to_uno = (ncol(data) - length(column_indexes))
  
  valueBox(value = tags$p(paste0(t(apply(data[nrow(data), 1:to_uno], 1, sort))[ncol(t(apply(data[nrow(data), 1:to_uno], 1, sort)))], ' %'), 
                          style = "font-size: 100%; color: #ffffff"), 
           icon = "fa-bar-chart",
           caption = tags$p(paste0(colnames(t(apply(data[nrow(data), 1:to_uno], 1, sort)))[ncol(t(apply(data[nrow(data), 1:to_uno], 1, sort)))], ' Mayor Incremento Mensual.'), style = "font-size: 100%; color: #ffffff"),
           color = '#e03fc8')
  
}

column_indexes = c('periodos', 'year', 'Mes', 'month', 'period_filter')

years_vector = unique(indec$year)





```



Precios
=========================================



Rows {data-height=150}
-------------------------------------

### Mensual


```{r}



renderValueBox({
    
  valuebox_mensual(indec, input$y)

})

```


### Interanual


```{r}



renderValueBox({
  
  valuebox_interanual(indec, input$y)
      
})


```


### Mayor Incremento Mensual

```{r}



renderValueBox({
  
  valuebox_mayor(indec)
  
})


```



Column {.sidebar} {data-height=100}
-------------------------------------

```{r}


selectInput("y", 
            label = tags$strong("Seleccionar Rubros", align = "center"),
            choices =  sort(names(indec[ ,!(colnames(indec) %in%  column_indexes)])), 
            selected = "salud")



```


Rows {data-height=850}
---------------------------------------------------------------

### {data-width=600}

```{r gráfico1}




renderHighchart({
  
      data = tibble(
        x = as.Date(indec$periodos[12:nrow(indec)]),
        y = round(((((pull(indec[,c(input$y)])/100)+1) *  ((lag(pull(indec[,c(input$y)]), 1)/100)+1) *  ((lag(pull(indec[,c(input$y)]), 2)/100)+1)		*  ((lag(pull(indec[,c(input$y)]), 3)/100)+1)*  ((lag(pull(indec[,c(input$y)]), 4)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 5)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 6)/100)+1)	*  ((lag(pull(indec[,c(input$y)]), 7)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 8)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 9)/100)+1)	*  ((lag(pull(indec[,c(input$y)]), 10)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 11)/100)+1) - 1 ) * 100),1)[12:nrow(indec)]
      )
      
      
      
      highcharter::hchart(
      data, type = "line",  highcharter::hcaes(x = "x", y = "y"),
      color = "rgba(29, 53, 87, 1)",
      name = str_to_title(gsub("_", " ", input$y)), 
      id = "trend",
      showInLegend = TRUE) %>%
      highcharter::hc_tooltip(crosshairs = TRUE, pointFormat = "Base: {point.y}") %>%
      
      highcharter::hc_plotOptions(
          line = list(
              color = "blue",
              marker = list(
                  fillColor = "white",
                  lineWidth = 2,
                  radius=1,
                  lineColor = NULL
              )
          )
      ) %>%
      highcharter::hc_legend(
          layout = "vertical",
          verticalAlign = "top",
          align = "right",
          floating = TRUE
      ) %>%
      highcharter::hc_xAxis(
          title = list(text = ""),
          gridLineWidth = 0,
          dateTimeLabelFormats = list(day = '%Y'),
          type = "datetime",
          reversed = FALSE
      ) %>%
      highcharter::hc_yAxis(
          title = list(text = str_to_title(gsub("_", " ", input$y))),
          gridLineWidth = 0,
          reversed = FALSE
      ) %>%
    
      highcharter::hc_caption(
          text = paste0("Serie Temporal de  ",str_to_title(gsub("_", " ", input$y)),". <br>Fuente: Indec.")) %>%
      highcharter::hc_tooltip(
          crosshairs = TRUE,
          backgroundColor = "#F0F0F0",
          shared = TRUE, 
          borderWidth = 5
      ) %>% 
      hc_title(
        text = paste0('Inflacion ', gsub('_', ' ', colnames(indec[,c(input$y)]))),
        style = list(fontSize = '16px', fontWeight = 'bold')) %>% 
      hc_subtitle(
        text = 'Desde 2017.',
        style = list(fontSize = '12px', color = "black")) %>% 
        
        hc_credits(enabled = TRUE, text = "Fuente: INDEC",align = "right",verticalAlign = "bottom",
    style = list(color = "#2b908f", fontSize = '10px'),
               href = " https://www.indec_total.gob.ar/ftp/cuadros/economia/sh_ipc_02_22.xls") 
      
})





```


### {data-width=400}

```{r}

renderHighchart({
    
    
  data2 = indec %>% 
    select(input$y, 'year') %>% 
    mutate(interanual = format(round((pull(indec[,c(input$y)]) / 100 ) + 1, 3), nsmall = 3))  %>%
    select('interanual', 'year') %>% 
    group_by(year) %>% 
    summarise(prod = format(round(prod(as.numeric(interanual)), 2), nsmall = 2)) %>% 
    mutate(interanual = (as.numeric(prod) - 1)*100)
  
  
  
  highcharter::hchart(
      data2, 
      type = "column",  
      highcharter::hcaes(x = "year", y = "interanual"),
      color = "#1b1b5e",
      name = str_to_title(gsub("_", " ", input$y)), 
      showInLegend = F,
         maxSize = "15%",
         dataLabels = list(enabled = TRUE,
                           format = '{point.y} %')) %>%
    hc_legend(enabled = FALSE) %>% 
      highcharter::hc_tooltip(
        crosshairs = FALSE, 
        pointFormat = "Inflacion: {point.y} %") %>%
      highcharter::hc_plotOptions(
          line = list(
              color = "red",
              marker = list(
                  fillColor = "white",
                  lineWidth = 2,
                  radius=1,
                  lineColor = NULL
              )
          )
      ) %>%
      highcharter::hc_xAxis(
          title = list(text = ""),
          gridLineWidth = 0,
          dateTimeLabelFormats = list(day = '%Y'),
          type = "date",
          reversed = FALSE
      ) %>%
      highcharter::hc_yAxis(
          title = list(text = str_to_title(gsub("_", " ", input$y))),
          gridLineWidth = 0,
          reversed = FALSE
      ) %>%
    
      highcharter::hc_caption(
          text = paste0("Serie Temporal de  ",str_to_title(gsub("_", " ", input$y)),". <br>Fuente: Indec.")) %>%
      hc_title(
        text = paste0('Inflacion ', gsub('_', ' ', colnames(indec[,c(input$y)]))),
        style = list(fontSize = '16px', fontWeight = 'bold')) %>% 
      hc_subtitle(
        text = 'Acumulada por año.',
        style = list(fontSize = '12px', color = "black")) %>% 
      highcharter::hc_tooltip(
          crosshairs = TRUE,
          backgroundColor = "#F0F0F0",
          shared = TRUE, 
          borderWidth = 5
      ) %>% 
        hc_credits(enabled = TRUE, text = "Fuente: INDEC",align = "right",verticalAlign = "bottom",
    style = list(color = "#2b908f", fontSize = '10px'),
               href = " https://www.indec_total.gob.ar/ftp/cuadros/economia/sh_ipc_02_22.xls")
  
  

})
```



