---
title: "Macro Trends Argentina"
output:
  flexdashboard::flex_dashboard:
     theme : spacelab
     orientation : rows 
     self_contained : TRUE
     css: www/styles.css
     navbar:
       - { title: "Fuente: Indec", href: "https://www.indec.gob.ar/", align: right}
runtime: shiny
---



```{r setup, include=FALSE}

#https://fontawesome.com/icons/chart-simple?s=solid
#https://shiny.rstudio.com/tutorial/written-tutorial/lesson3/
#https://fontawesome.com/v4/cheatsheet/


library(flexdashboard)
library(tidyverse)
library(shiny)
library(readxl)
library(highcharter)
library(RColorBrewer)


source("downloadData.R")

indec = read_excel("indecnacional.xlsx")

indec$period_filter = substr(as.Date(indec$periodos), 1, 7)



interanual <- function(df, val){
    values = c()
    for (i in 0:11) {
        value_lag = lag((pull((df[,c(val)]) / 100) + 1), i)[nrow(df)]
        values[i + 1] <- value_lag}
    product = (prod(values) - 1) * 100
    return(round(product,1))
}

valuebox_mensual = function(data, inputy) {
  valueBox(
    value = tags$p(paste0(pull(data[,c(inputy)])[nrow(data)], ' %'),
                   style = "font-size: 100%; color: #ffffff"), 
    icon = "fa-diamond",
    caption = tags$p(paste0(substr(data$periodos[nrow(data)],1,7), ' ',inputy,' : Mensual'), 
                     style = "font-size: 100%; color: #ffffff"),
    color = '#4dc5ba')
  
}



valuebox_interanual = function(data, inputy) {
  
  valueBox(value = tags$p(paste0(interanual(data, inputy), ' %'), 
                          style = "font-size: 100%; color: #ffffff"), 
           icon = "fa-line-chart",
           caption = tags$p(paste0(paste0('Desde: ',substr(data$periodos[nrow(data) - 12],1,7), ' Hasta ', substr(data$periodos[nrow(data)],1,7)), '. Interanual.'), style = "font-size: 100%; color: #ffffff"),
           color = '#525cd1')
  
}


valuebox_mayor = function(data) {
  
  to_uno = (ncol(data) - length(column_indexes))
  
  valueBox(value = tags$p(paste0(t(apply(data[nrow(data), 1:to_uno], 1, sort))[ncol(t(apply(data[nrow(data), 1:to_uno], 1, sort)))], ' %'), 
                          style = "font-size: 100%; color: #ffffff"), 
           icon = "fa-bar-chart",
           caption = tags$p(paste0(colnames(t(apply(data[nrow(data), 1:to_uno], 1, sort)))[ncol(t(apply(data[nrow(data), 1:to_uno], 1, sort)))], ' Mayor Incremento Mensual.'), style = "font-size: 100%; color: #ffffff"),
           color = '#e03fc8')
  
}

column_indexes = c('periodos', 'year', 'Mes', 'month', 'period_filter')

years_vector = unique(indec$year)


```



Precios
=========================================



Rows {data-height=150}
-------------------------------------

### Mensual


```{r}



renderValueBox({
    
  valuebox_mensual(indec, input$y)

})

```


### Interanual


```{r}



renderValueBox({
  
  valuebox_interanual(indec, input$y)
      
})


```


### Mayor Incremento Mensual

```{r}



renderValueBox({
  
  valuebox_mayor(indec)
  
})


```



Column {.sidebar} {data-height=100}
-------------------------------------

```{r}


selectInput("y", 
            label = tags$strong("Seleccionar Rubros", align = "center"),
            choices =  sort(names(indec[ ,!(colnames(indec) %in%  column_indexes)])), 
            selected = "salud")



```


Rows {data-height=850}
---------------------------------------------------------------

### {data-width=600}

```{r gráfico1}



renderHighchart({
      
      
       highchart() %>% 
          hc_xAxis(categories = as.Date(indec$periodos[12:nrow(indec)]), 
      dateTimeLabelFormats = list(week = "%b-%y")) %>% 
          hc_chart(type = "line") %>% 
          hc_add_series(name = "Periodo", data = round(((((pull(indec[,c(input$y)])/100)+1) *  ((lag(pull(indec[,c(input$y)]), 1)/100)+1) *  ((lag(pull(indec[,c(input$y)]), 2)/100)+1)		*  ((lag(pull(indec[,c(input$y)]), 3)/100)+1)*  ((lag(pull(indec[,c(input$y)]), 4)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 5)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 6)/100)+1)	*  ((lag(pull(indec[,c(input$y)]), 7)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 8)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 9)/100)+1)	*  ((lag(pull(indec[,c(input$y)]), 10)/100)+1)				*  ((lag(pull(indec[,c(input$y)]), 11)/100)+1) - 1 ) * 100),1)[12:nrow(indec)], color = "black") %>% 

          hc_title(text = paste0('Inflacion ', gsub('_', ' ', colnames(indec[,c(input$y)]))),
                   style = list(fontSize = '25px', fontWeight = 'bold')) %>% 
          hc_tooltip(crosshairs = TRUE, backgroundColor = "#FCFFC5",
                 shared = TRUE, borderWidth = 2) %>%
          hc_subtitle(text = 'Desde 2017.',
                      style = list(fontSize = '16px', color = "black")) %>% 
          hc_credits(enabled = TRUE, text = "Fuente: INDEC",align = "right",verticalAlign = "bottom",
    style = list(color = "#2b908f", fontSize = '10px'),
               href = " https://www.indec_total.gob.ar/ftp/cuadros/economia/sh_ipc_02_22.xls") 
    
})





```


### {data-width=400}

```{r}

renderHighchart({
    
    
  data = indec %>% 
    select(input$y, 'year') %>% 
    mutate(interanual = format(round((pull(indec[,c(input$y)]) / 100 ) + 1, 3), nsmall = 3))  %>%
    select('interanual', 'year') %>% 
    group_by(year) %>% 
    summarise(prod = format(round(prod(as.numeric(interanual)), 2), nsmall = 2)) %>% 
    mutate(interanual = (as.numeric(prod) - 1)*100)
  

  data %>%
     hchart('column', hcaes(x = year, y = interanual),
         showInLegend = F,
         borderColor = "black",
         maxSize = "15%",
         dataLabels = list(enabled = TRUE, 
                           format = '{point.y} %')) %>%
    hc_title(text = paste0('Inflacion ',input$y,' anual'),
             style = list(fontSize = '25px', fontWeight = 'bold')) %>% 
    hc_yAxis(labels = list(style = list(color = "black")),
           tickColor = "black") %>% 
    hc_xAxis(labels = list(style = list(color = "black")),
           tickColor = "black") %>% 
    hc_tooltip(pointFormat =  "{series.name} <br>
    {point.y} %", crosshairs = TRUE, backgroundColor = "#FCFFC5",
                 shared = TRUE, borderWidth = 2) %>%
    hc_add_theme(hc_theme_elementary())  %>% 
    hc_colors(c("#f777a0")) %>% 
    hc_credits(enabled = TRUE, text = "Fuente: INDEC",align = "right",verticalAlign = "bottom",
    style = list(color = "#2b908f", fontSize = '10px'),
               href = " https://www.indec_total.gob.ar/ftp/cuadros/economia/sh_ipc_02_22.xls") 

})
```


Grafico de Barras
=========================================



Rows {data-height=150}
-------------------------------------

### Mensual


```{r}

renderValueBox({
    
  valuebox_mensual(indec, input$y_dos_2)

})



```


### Interanual


```{r}

renderValueBox({
  
  valuebox_interanual(indec, input$y_dos_2)
      
})



```


### Mayor Incremento Mensual

```{r}


renderValueBox({
  
  valuebox_mayor(indec)
  
})



```


Column {.sidebar} {data-height=100}
-------------------------------------

```{r}



selectInput("y_dos_2", label = tags$strong("Seleccionar Rubros", align = "center"), choices = gsub("_", " ", sort(names(indec[,-c(14,15,16,17,18)]))))

br()



selectInput(
    inputId =  "date_one_1", 
    label = tags$strong("Año 1", align = "center"), 
    choices = years_vector,
    selected = 2017
)

selectInput(
    inputId =  "date_two_2", 
    label = tags$strong("Año 2", align = "center"), 
    choices = years_vector,
    selected = 2022
)


observe({
        if(!is.null(input$date_two_2))
            updateSelectInput(session, "date_one_1", 
                              choices = years_vector[!(years_vector %in% input$date_two_2)], 
                              selected = isolate(input$date_one_1))})
observe({
        if(!is.null(input$date_one_1))
            updateSelectInput(session, "date_two_2", 
                              choices = years_vector[!(years_vector %in% input$date_one_1)], 
                              selected = isolate(input$date_two_2) )})


```


Rows {data-height=850}
---------------------------------------------------------------

### Índice de precios al consumidor con cobertura nacional

```{r}

renderHighchart({
  

    indec_totalgrafic <- highchart() %>%
    hc_chart(type = "column")  %>%
    hc_title(text = paste0('Inflacion ',input$y_dos_2),
             style = list(fontSize = '25px', fontWeight = 'bold')) %>% 
    hc_xAxis(categories = indec$month,
             title = 'Year',
             title = list(text = "Mes")) %>%
    hc_add_series(name = input$date_one_1,
                  data = pull(indec[,c(input$y_dos_2)])[indec$year == input$date_one_1]) %>%
    hc_add_series(name = input$date_two_2,
                  data = pull(indec[,c(input$y_dos_2)])[indec$year == input$date_two_2]) %>%
    hc_yAxis(title = list(text = "Porcentaje")) %>% 
    hc_tooltip(pointFormat =  "{series.name} <br>
    {point.y} %", crosshairs = TRUE) %>%
    hc_add_theme(hc_theme_elementary())  %>% 
    hc_colors(c("#f777a0","#a60538")) %>% 
    hc_credits(enabled = TRUE, text = "Fuente: INDEC",align = "right",verticalAlign = "bottom",
    style = list(color = "#2b908f", fontSize = '10px'),
               href = " https://www.indec_total.gob.ar/ftp/cuadros/economia/sh_ipc_02_22.xls") %>%
    hc_add_theme(hc_theme_google())
    
  

  
})



```


