
name: Run on push master, main

# Cuando se ejecutara la accion
on:
  # Activa el flujo de trabajo en eventos de solicitud push o pull, pero solo para la rama principal
  push:
    branches: [ main, master ]

    
  workflow_run:
    workflows: ["Update data"]
    types:
      - completed

  # Una vez terminado el workflow llamado Update data se ejecutan los siguientes jobs:
  workflow_dispatch:

jobs:
  # Nombre del job:
  build:
    runs-on: Ubuntu-20.04

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # build the docker image and give it the name main
      - name: Build image
        run: docker build -t main . 

      # run the docker image supply the secrets from the github secrets store.  
      - name: execute
        run: >
          docker run 
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} 
          -e TOKEN=${{secrets.TOKEN}} 
          -e SECRET=${{secrets.SECRET}} 
          main
