
name: Run on push master, main

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master ]
  schedule:  
    - cron:  '0 */12 * * *'
    # cada doce horas '0 */12 * * *'
    # cada 10 min '*/10 * * * *'
    # '0 0 * * *' # Ejecuta el cron una vez al día a las 00:00 UTC
    
  workflow_run:
    workflows: ["Update data"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # build the docker image and give it the name main
      - name: Build image
        run: docker build -t main . 

      - name: Install dependencies
        run: |
          install.packages(c("rtweet","highcharter", "XML", "rlist", "flexdashboard", "tidyverse", "shiny", "readxl", "RColorBrewer", "httr", "lubridate", "writexl"))
        shell: Rscript {0}

      # run the docker image supply the secrets from the github secrets store.  
      - name: execute
        run: >
          docker run 
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} 
          -e TOKEN=${{secrets.TOKEN}} 
          -e SECRET=${{secrets.SECRET}} 
          main
